# Generated by Django 3.1.4 on 2020-12-16 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('assunto', models.CharField(max_length=100, verbose_name='assunto')),
                ('mensagem', models.CharField(max_length=2000, verbose_name='mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200, verbose_name='autor')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado_em')),
            ],
        ),
    ]
