# Generated by Django 3.1.5 on 2021-01-10 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210106_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1000, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em:'),
        ),
    ]
