# Generated by Django 3.1.5 on 2021-01-05 14:39

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado em: ')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado em:')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('color', models.CharField(max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado em: ')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado em:')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('img', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('text', models.TextField(verbose_name='Texto')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
