# Generated by Django 3.1.5 on 2021-01-05 14:57

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210105_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=stdimage.models.StdImageField(blank=True, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
