# Generated by Django 3.1.5 on 2021-01-16 00:45

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210110_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=stdimage.models.StdImageField(blank=True, upload_to='media/<function get_file_path at 0x039D3190>', verbose_name='Imagem'),
        ),
    ]
