# Generated by Django 3.1.5 on 2021-02-28 23:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
