# Generated by Django 3.1.5 on 2021-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210228_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1000, unique=True, verbose_name='Slug'),
        ),
    ]
