# Generated by Django 3.1.5 on 2021-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210301_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1000, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Associação Catarinense de Tradutores e Intértpretes de Liguagem de Sinais', max_length=200, verbose_name='Autor'),
        ),
    ]
