# Generated by Django 3.1.5 on 2021-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210301_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='translation',
            field=models.TextField(blank=True, verbose_name='Tradução para LIBRAS'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Cor (em hexadecimal)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='ACATILS', max_length=200, verbose_name='Autor'),
        ),
    ]
